# -*- coding: utf-8 -*-

import json
import logging

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)
"""week 8_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VtSec7w5E1SRVJwyji7dAdPkJC4enZsa

# 🧠 Single Agent Pipeline Project

## Problem Statement
Build a **Single-Agent Smart Assistant** that:
- Understands user queries
- Routes tasks based on intent
- Uses tools when required
- Returns structured JSON output

### The agent should handle:
- Math queries → Calculator Tool
- Keyword extraction → Keyword Tool
- General queries → Direct response

---
### 🛠️ What You Need to Implement
- Agent logic
- Conditional routing
- Tool integration
- Basic error handling

### 🚀 Bonus
- Improve routing
- Add logging
- Add more tools
"""

# 🛠️ TOOL 1: Calculator

def calculator(expression: str) -> str:
    """Evaluate a mathematical expression."""
    try:
        return str(eval(expression))
    except Exception:
        return "Error in calculation"

# 🛠️ TOOL 2: Keyword Extractor

def extract_keywords(text: str) -> list:
    """Extract keywords from text."""
    try:
        words = text.split()

        keywords = list(set([
            w.lower()
            for w in words
            if len(w) > 4
        ]))

        return keywords[:5]

    except Exception:
        return []

"""## 🤖 Implement Agent Logic Below

👉 Use conditional routing:
- If query contains "calculate" → use calculator
- If query contains "keywords" → use keyword extractor
- Else → general response
"""

# 🤖 AGENT FUNCTION

def agent(query: str):
    """Route a query to the appropriate tool and return a structured dictionary."""
    try:
        if not isinstance(query, str) or not query.strip():
            logger.warning("Invalid or empty query received")
            return {
                "type": "error",
                "result": "Query must be a non-empty string"
            }

        query_lower = query.lower().strip()
        logger.info("Processing query: %s", query)

        # Route 1: Calculator
        if "calculate" in query_lower:
            expression = query_lower.split("calculate", 1)[1].strip()

            if not expression:
                logger.warning("Missing mathematical expression")
                return {
                    "type": "error",
                    "result": "No mathematical expression provided"
                }

            result = calculator(expression)

            if result == "Error in calculation":
                logger.warning("Invalid mathematical expression: %s", expression)
                return {
                    "type": "error",
                    "result": result
                }

            response = {
                "type": "calculation",
                "result": result
            }
            logger.info("Calculation completed successfully")
            return response

        # Route 2: Keyword Extractor
        elif "keywords" in query_lower:
            text = query_lower.split("keywords", 1)[1].strip()

            if text.startswith("from "):
                text = text[5:].strip()

            if not text:
                logger.warning("Missing text for keyword extraction")
                return {
                    "type": "error",
                    "result": "No text provided for keyword extraction"
                }

            result = extract_keywords(text)

            response = {
                "type": "keywords",
                "result": result
            }
            logger.info("Keyword extraction completed successfully")
            return response

        # Route 3: General Response
        else:
            response = {
                "type": "general",
                "result": f"You asked: {query}"
            }
            logger.info("General query routed to fallback")
            return response

    except Exception as e:
        logger.exception("Agent processing failed")
        return {
            "type": "error",
            "result": str(e)
        }

"""## 📦 Expected Output Format

```
{
  "type": "calculation / keywords / general / error",
  "result": ...
}
```
"""

# 🧪 TEST CASES

queries = [
    "Calculate 20 + 5",
    "Extract keywords from Artificial Intelligence is transforming industries",
    "What is machine learning?"
]

for q in queries:

    print("Query:", q)
    print("Response:", json.dumps(agent(q), ensure_ascii=False))
    print("-" * 50)

# 🎯 INTERACTIVE MODE

while True:

    user_input = input(
        "Enter query (type 'exit' to stop): "
    )

    if user_input.lower() == "exit":
        break

    print("Response:", json.dumps(agent(user_input), ensure_ascii=False))

